name: NLPprocessing
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.4=py39h02fc5c5_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39h02fc5c5_3
  - arrow-cpp=11.0.0=hce30654_3_cpu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - aws-c-auth=0.6.23=h2971766_1
  - aws-c-cal=0.5.20=hef34eba_4
  - aws-c-common=0.8.9=h1a8c8d9_0
  - aws-c-compression=0.2.16=hfc83f9a_1
  - aws-c-event-stream=0.2.18=hcd30925_2
  - aws-c-http=0.7.3=he9760f3_1
  - aws-c-io=0.13.14=h966d345_3
  - aws-c-mqtt=0.8.6=hb11de44_1
  - aws-c-s3=0.2.3=h7911ba3_3
  - aws-c-sdkutils=0.1.7=hfc83f9a_1
  - aws-checksums=0.1.14=hfc83f9a_1
  - aws-crt-cpp=0.18.16=h4ff3756_13
  - aws-sdk-cpp=1.10.57=hce8d117_2
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - brotlipy=0.7.0=py39h02fc5c5_1005
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.12.7=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cffi=1.15.1=py39h7e6b969_3
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.7=py39haaf3ac1_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.10.0=pyhd8ed1ab_0
  - debugpy=1.6.6=py39h23fbdae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - filelock=3.9.0=pyhd8ed1ab_0
  - flatbuffers=22.12.06=hb7217d7_2
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fonttools=4.38.0=py39h02fc5c5_1
  - freetype=2.12.1=hd633e50_1
  - frozenlist=1.3.3=py39h02fc5c5_0
  - fsspec=2023.1.0=pyhd8ed1ab_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.21.1=h0186832_0
  - gflags=2.2.2=hc88da5d_1004
  - giflib=5.2.1=h27ca646_2
  - glog=0.6.0=h6da1cb0_0
  - google-auth=2.16.0=pyh1a96a4e_1
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.51.1=py39h3adb8dc_1
  - h5py=3.8.0=nompi_py39hbcdb4fd_101
  - hdf5=1.14.0=nompi_h6b85c65_102
  - huggingface_hub=0.12.1=pyhd8ed1ab_0
  - icu=70.1=h6b3803e_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - ipykernel=6.21.1=pyh736e0ef_0
  - ipython=8.9.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h1a8c8d9_3
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py39h2804cbe_8
  - jupyter_client=8.0.2=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py39h2804cbe_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.2.1=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - keras=2.11.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39haaf3ac1_1
  - krb5=1.20.1=h69eda48_0
  - lcms2=2.14=h481adae_1
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20220623.0=cxx17_h28b99d4_6
  - libaec=1.0.6=hb7217d7_1
  - libarrow=11.0.0=hd179924_3_cpu
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=7.87.0=h9049daf_0
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.17=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.10=h7673551_4
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_27
  - libgfortran5=11.3.0=hdaf2cc0_27
  - libgoogle-cloud=2.7.0=hcf11473_1
  - libgrpc=1.51.1=hb15be72_1
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.51.0=hae82a92_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=3.21.12=hb5ab8b9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libthrift=0.16.0=h6635e49_2
  - libtiff=4.5.0=h5dffbdd_2
  - libunistring=0.9.10=h3422bc3_0
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.7=h7cfbb63_0
  - lz4-c=1.9.4=hb7217d7_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.2=py39h02fc5c5_0
  - matplotlib-base=3.6.3=py39h35e9e80_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - multidict=6.0.4=py39h02fc5c5_0
  - multiprocess=0.70.14=py39h02fc5c5_3
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.5.1=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openpyxl=3.1.1=py39h02fc5c5_0
  - openssl=3.0.8=h03a7124_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - orc=1.8.2=hef0d403_2
  - packaging=23.0=pyhd8ed1ab_0
  - pandoc=2.19.2=hce30654_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h8bd98a6_1
  - pip=23.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - prompt_toolkit=3.0.36=hd8ed1ab_0
  - psutil=5.9.4=py39h02fc5c5_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=11.0.0=py39hfdcab31_3_cpu
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py39h02fc5c5_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=hea58f1e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-flatbuffers=23.1.21=pyhd8ed1ab_0
  - python-json-logger=2.0.4=pyhd8ed1ab_0
  - python-xxhash=3.2.0=py39h02fc5c5_0
  - python_abi=3.9=3_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39h02fc5c5_5
  - pyzmq=25.0.0=py39h0553236_0
  - re2=2023.02.01=hb7217d7_0
  - readline=8.1.2=h46ed386_0
  - regex=2022.10.31=py39h02fc5c5_0
  - requests=2.28.2=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - responses=0.18.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rsa=4.9=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h156473d_2
  - smart_open=6.3.0=pyhd8ed1ab_1
  - snappy=1.1.9=h17c5cce_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py39h4d8bf0d_2
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py39he2a39a8_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.11.0=cpu_py39h2839aeb_0
  - tensorflow-base=2.11.0=cpu_py39h072764a_0
  - tensorflow-estimator=2.11.0=cpu_py39hda8e89f_0
  - termcolor=2.2.0=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tokenizers=0.13.2=py39h6120d9b_0
  - tornado=6.2=py39h02fc5c5_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - transformers=4.26.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - unicodedata2=15.0.0=py39h02fc5c5_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.0=pyhd8ed1ab_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - wrapt=1.14.1=py39h02fc5c5_1
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xxhash=0.8.1=h1a8c8d9_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.8.2=py39h02fc5c5_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.12.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=hf913c23_6
  - pip:
      - adjusttext==0.8
      - annoy==1.17.1
      - async-generator==1.10
      - attrs==22.2.0
      - bert-for-tf2==0.14.9
      - bio==1.5.8
      - biopython==1.81
      - biothings-client==0.2.6
      - blis==0.7.9
      - bs4==0.0.1
      - catalogue==2.0.8
      - certifi==2022.12.7
      - charset-normalizer==3.0.1
      - chemdataextractor==1.3.0
      - click==7.1.2
      - community==1.0.0b1
      - confection==0.0.4
      - conllu==4.5.2
      - cryptography==39.0.0
      - cssselect==1.2.0
      - cymem==2.0.7
      - cython==0.29.33
      - dawg==0.8.0
      - emmet-core==0.42.13
      - en-core-sci-sm==0.4.0
      - en-core-web-sm==3.5.0
      - en-ner-bc5cdr-md==0.4.0
      - en-ner-bionlp13cg-md==0.4.0
      - en-ner-jnlpba-md==0.4.0
      - exceptiongroup==1.1.1
      - flask==2.2.3
      - forceatlas2==1.0
      - fst-pso==1.8.1
      - future==0.18.3
      - fuzzytm==2.0.5
      - gensim==3.8.3
      - gprofiler-official==1.0.0
      - h11==0.14.0
      - hdbscan==0.8.29
      - igraph==0.10.4
      - iniconfig==2.0.0
      - itsdangerous==2.1.2
      - json5==0.9.5
      - jsonmerge==1.9.0
      - jsonpickle==3.0.1
      - langcodes==3.3.0
      - langdetect==1.0.7
      - latexcodec==2.0.1
      - leidenalg==0.9.1
      - libclang==15.0.6.1
      - llvmlite==0.39.1
      - lxml==4.9.2
      - mat2vec==0.2
      - miniful==0.0.6
      - monty==2022.9.9
      - mp-api==0.30.8
      - mpmath==1.2.1
      - msgpack==1.0.4
      - murmurhash==1.0.9
      - mygene==3.2.2
      - networkx==3.0
      - nltk==3.8.1
      - nmslib==2.1.1
      - numba==0.56.4
      - numpy==1.23.5
      - outcome==1.2.0
      - palettable==3.3.0
      - pandas==1.5.3
      - params-flow==0.8.2
      - pathy==0.10.1
      - pdflatex==0.1.3
      - pdfminer-six==20221105
      - plotly==5.13.0
      - pluggy==1.0.0
      - powerlaw==1.5
      - pprintpp==0.4.0
      - preshed==3.0.8
      - protobuf==3.19.6
      - py-params==0.10.2
      - pybase64==1.2.3
      - pybind11==2.6.1
      - pybtex==0.24.0
      - pydantic==1.8.2
      - pyfume==0.2.25
      - pymatgen==2023.1.30
      - pyner==0.0.13
      - pynndescent==0.5.8
      - pysbd==0.3.4
      - pytest==7.2.2
      - python-crfsuite==0.9.9
      - python-docx==0.8.11
      - python-louvain==0.16
      - pyvis==0.3.2
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - scikit-learn==1.2.1
      - scipy==1.10.0
      - scispacy==0.5.1
      - selenium==4.8.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.97
      - setuptools==67.1.0
      - simpful==2.9.0
      - sortedcontainers==2.4.0
      - spacy==3.4.4
      - spacy-langdetect==0.1.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - spglib==2.0.2
      - srsly==2.4.6
      - sympy==1.11.1
      - tabulate==0.9.0
      - tenacity==8.1.0
      - tensorflow-hub==0.12.0
      - tensorflow-macos==2.11.0
      - texttable==1.6.7
      - thinc==8.1.9
      - threadpoolctl==3.1.0
      - tomli==2.0.1
      - torch==2.1.0.dev20230305
      - torchaudio==2.0.0.dev20230305
      - torchvision==0.15.0.dev20230305
      - trio==0.22.0
      - trio-websocket==0.10.0
      - typer==0.3.2
      - umap-learn==0.5.3
      - uncertainties==3.1.7
      - unidecode==1.3.6
      - wasabi==0.10.1
      - wget==3.2
      - wsproto==1.2.0
      - xlsxwriter==3.0.8
prefix: /opt/homebrew/anaconda3/envs/NLPprocessing
